include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "/*.g.dart"
    - "/*.gen.dart"
    - "/*.freezed.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"