include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "*.g.dart"
    - "/*.g.dart"
    - "/*.gen.dart"
    - "/*.freezed.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "*/firebase_options.dart"
    - "*/generated/"

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars : false